"""
seed_context_scores.py — Populate query_context_scores table at startup.

Questions scored 0.0–1.0 on how much document context they require:
  0.0  = no context needed (author identity, meta-literary knowledge)
  0.5  = moderate (technique analysis, thematic interpretation)
  1.0  = full context required (passage-specific, plot details)

Sources: Questions database_FINISHED.pdf + supplementary IB English A questions.
"""
from __future__ import annotations

import logging
from database import get_connection, get_db_path

logger = logging.getLogger(__name__)

# (question, score, category)
_QUESTIONS: list[tuple[str, float, str]] = [
    # ── work_identity ──────────────────────────────────────────────────────
    ("Who is the author of this book?", 0.00, "work_identity"),
    ("What genre is this work?", 0.05, "work_identity"),
    ("When was this book published?", 0.05, "work_identity"),
    ("What is the title of the work you are studying?", 0.00, "work_identity"),
    ("Have you heard about this author till now?", 0.00, "work_identity"),
    ("Have you heard about this book till now? In which context or circumstance?", 0.05, "work_identity"),
    ("Who do you think the text was originally written for?", 0.10, "work_identity"),
    ("Which global issue is this book related to?", 0.10, "work_identity"),

    # ── meta_literary ──────────────────────────────────────────────────────
    ("What is the purpose of studying literature and what do we gain from it?", 0.00, "meta_literary"),
    ("Why do you think literature is still important today?", 0.00, "meta_literary"),
    ("Can the same text be understood in different ways? Why?", 0.05, "meta_literary"),
    ("Do you think there is one correct interpretation or many valid ones? Explain.", 0.05, "meta_literary"),
    ("What makes an interpretation strong or convincing?", 0.05, "meta_literary"),
    ("Why is using evidence from the text important?", 0.05, "meta_literary"),
    ("How can readers interpret the same text in different ways?", 0.05, "meta_literary"),
    ("What makes a literary text become a classic?", 0.05, "meta_literary"),
    ("Who decides which texts become classics?", 0.05, "meta_literary"),
    ("What social, political, or cultural power structures influence which texts are valued?", 0.05, "meta_literary"),
    ("Why might some authors or cultures be excluded from the literary canon?", 0.05, "meta_literary"),
    ("How do definitions of classic differ across countries and cultures?", 0.05, "meta_literary"),
    ("What personal criteria do you use to decide whether a text deserves classic status?", 0.05, "meta_literary"),
    ("Can a literary text have a negative or harmful effect on its audience?", 0.05, "meta_literary"),
    ("When, if ever, is censoring a literary text justified?", 0.05, "meta_literary"),
    ("Do you think form and meaning can be separated, or are they always connected? Explain your idea.", 0.05, "meta_literary"),
    ("Why might a literary text be valuable even if it does not give direct facts?", 0.05, "meta_literary"),
    ("Is it fair or useful to analyze older texts using modern values and ideas?", 0.05, "meta_literary"),
    ("What are the limits of doing this?", 0.05, "meta_literary"),
    ("What special skills do you need to read and analyze a poem or novel (for example, noticing imagery or symbolism)?", 0.05, "meta_literary"),
    ("How is reading a poem or story different from reading a news article about the same topic?", 0.05, "meta_literary"),
    ("How does language change depending on the type of text?", 0.10, "meta_literary"),
    ("What language features are typical of this literary form (novel, play, poem, graphic text)?", 0.10, "meta_literary"),
    ("Do a poem and an informational text have different values to you as a reader?", 0.05, "meta_literary"),
    ("What emotions or ideas does a literary text create compared to an informational text?", 0.10, "meta_literary"),
    ("What does literature help you understand that factual texts may not?", 0.05, "meta_literary"),
    ("Do literary forms (poems, plays, novels) restrict writers or help them create meaning?", 0.05, "meta_literary"),
    ("How can authors break or adapt rules to create new effects?", 0.10, "meta_literary"),
    ("Does knowing literary rules and conventions make a text easier to understand, or can it sometimes confuse readers?", 0.05, "meta_literary"),
    ("When might too much technical knowledge about literature reduce enjoyment or personal engagement?", 0.05, "meta_literary"),
    ("How can reading inspire writers to reshape or recreate earlier texts?", 0.05, "meta_literary"),
    ("How is meaning created and understood in a literary text?", 0.10, "meta_literary"),
    ("What are the typical features of this type of text (for example poem, play, novel, speech)?", 0.10, "meta_literary"),
    ("How does placing a text into a genre or category influence how readers interpret it?", 0.15, "meta_literary"),
    ("Can labeling a text limit or shape what readers notice or expect?", 0.10, "meta_literary"),
    ("To what extent can literary texts be used as sources of historical information?", 0.10, "meta_literary"),
    ("Why might some translations be more effective than others?", 0.05, "meta_literary"),
    ("How can reviews, critics, teachers, or classmates shape the way you understand a text?", 0.05, "meta_literary"),
    ("Can popular opinion change the perceived meaning or value of a literary work?", 0.05, "meta_literary"),
    ("What have you learned about literature by studying these texts?", 0.10, "meta_literary"),

    # ── historical_cultural_context ────────────────────────────────────────
    ("What is the socio-cultural background of the work?", 0.15, "historical_cultural_context"),
    ("What is the historical context in which the work has been written?", 0.15, "historical_cultural_context"),
    ("What are the main historical events from the time the author of the work you are reading lived?", 0.10, "historical_cultural_context"),
    ("What are the main events in the life of the author you are studying?", 0.10, "historical_cultural_context"),
    ("Can an author write successfully about a culture of which they are not a part of?", 0.05, "historical_cultural_context"),
    ("What social, historical, or cultural context influenced the author?", 0.15, "historical_cultural_context"),
    ("What historical or cultural factors influenced the author when writing this text?", 0.20, "historical_cultural_context"),
    ("Why does the time and culture in which a text is written and read matter?", 0.10, "historical_cultural_context"),
    ("How might these conditions shape the characters and themes?", 0.20, "historical_cultural_context"),
    ("How might the original audience have understood this text differently from modern readers?", 0.20, "historical_cultural_context"),
    ("Which historical or social changes could alter the interpretation of this work?", 0.20, "historical_cultural_context"),
    ("How well can a modern reader understand a text that was written in a very different historical or cultural context?", 0.15, "historical_cultural_context"),
    ("What problems or risks can occur when an author writes about a culture they do not belong to?", 0.10, "historical_cultural_context"),
    ("Is what we learn about a culture from literature always accurate or reliable?", 0.10, "historical_cultural_context"),
    ("What can literature teach us about the beliefs, values, and traditions of a culture?", 0.10, "historical_cultural_context"),
    ("How much can literature teach us about another culture?", 0.10, "historical_cultural_context"),
    ("What can readers from different cultures or time periods learn from a literary text?", 0.10, "historical_cultural_context"),
    ("How does the translator's time and cultural context influence the translation?", 0.10, "historical_cultural_context"),
    ("How can readers judge whether a translation is good quality?", 0.05, "historical_cultural_context"),
    ("What meaning or effects might be lost or changed in translation?", 0.15, "historical_cultural_context"),
    ("What differences do you notice between reading a text in the original language and in translation?", 0.15, "historical_cultural_context"),
    ("How could language barriers or translation affect meaning?", 0.15, "historical_cultural_context"),
    ("What difficulties can modern readers face when reading this text?", 0.15, "historical_cultural_context"),
    ("How should we approach texts that come from unfamiliar contexts?", 0.10, "historical_cultural_context"),
    ("What aspects of this text feel unfamiliar or different from your own culture or time?", 0.20, "historical_cultural_context"),
    ("How important is knowing the background (time, place, culture) of a text for understanding its meaning?", 0.15, "historical_cultural_context"),

    # ── reader_response ────────────────────────────────────────────────────
    ("Was this your experience with the work so far?", 0.05, "reader_response"),
    ("What is your experience with the work so far?", 0.05, "reader_response"),
    ("Was this book difficult for you to understand?", 0.05, "reader_response"),
    ("Did you have to do research to fully understand this book?", 0.05, "reader_response"),
    ("Was this book revealing another meaning after a second reading?", 0.10, "reader_response"),
    ("What feedback have you received and how will you apply it?", 0.05, "reader_response"),
    ("What was your biggest challenge in this task?", 0.05, "reader_response"),
    ("What progress are you most proud of?", 0.05, "reader_response"),
    ("What new skills or knowledge did you develop while studying this work?", 0.10, "reader_response"),
    ("What was difficult for you and how did you overcome it?", 0.05, "reader_response"),
    ("What strategies helped you improve your analysis or writing?", 0.05, "reader_response"),
    ("What did you personally learn from reading this work?", 0.10, "reader_response"),
    ("What emotions or thoughts did this text make you feel or have?", 0.15, "reader_response"),
    ("How did this text affect your thoughts, emotions, or values?", 0.15, "reader_response"),
    ("Which issue has this book confirmed or deepened your views on?", 0.15, "reader_response"),
    ("How has this book confirmed or deepened your views?", 0.15, "reader_response"),
    ("How has this book impacted the way you think about writing?", 0.10, "reader_response"),
    ("How has this book impacted the way you think about this topic?", 0.10, "reader_response"),
    ("How has this book impacted the way you think about reading?", 0.10, "reader_response"),
    ("What was it about the work that transformed your thinking?", 0.15, "reader_response"),
    ("What were your first impressions of the text?", 0.15, "reader_response"),
    ("What questions did the text raise for you?", 0.20, "reader_response"),
    ("What do you need to research further?", 0.10, "reader_response"),
    ("How has your understanding of the text changed since your first reading?", 0.20, "reader_response"),
    ("How has rereading this text changed your interpretation over time?", 0.20, "reader_response"),
    ("How has interpreting this text changed the way you think about its themes or characters?", 0.30, "reader_response"),
    ("Did this text make you question your beliefs or assumptions? How?", 0.15, "reader_response"),
    ("Did the story make you reflect on issues outside the text (for example society, relationships, power, or identity)?", 0.15, "reader_response"),
    ("In what ways can this text be both enjoyable to read and useful for academic analysis?", 0.15, "reader_response"),
    ("What new ideas or perspectives did this text help you understand?", 0.20, "reader_response"),
    ("Did you identify with any character or situation? Why?", 0.20, "reader_response"),
    ("How did these challenges help you think more deeply about the topic?", 0.10, "reader_response"),
    ("What specific questions do you want feedback on?", 0.05, "reader_response"),
    ("Which part of your analysis are you least confident about?", 0.05, "reader_response"),
    ("How can you improve your argument based on your tutor's comments?", 0.05, "reader_response"),
    ("What parts of the text were difficult, uncomfortable, or challenging to read?", 0.35, "reader_response"),
    ("How might different readers react differently to this same text?", 0.25, "reader_response"),

    # ── theme_interpretation ───────────────────────────────────────────────
    ("What is the main aim of the work that you are studying? How do you know this?", 0.30, "theme_interpretation"),
    ("Why do you think the author wrote this work?", 0.25, "theme_interpretation"),
    ("What is the central idea or message of this work?", 0.30, "theme_interpretation"),
    ("Which is the point of view presented by this book?", 0.30, "theme_interpretation"),
    ("What global issue does this text engage with (power, inequality, identity, conflict, environment)?", 0.25, "theme_interpretation"),
    ("Which concept is most relevant to this work and why?", 0.30, "theme_interpretation"),
    ("Which is the main topic of this book?", 0.25, "theme_interpretation"),
    ("How successfully has the book presented a particular point of view?", 0.40, "theme_interpretation"),
    ("How similar is the world in the work you are reading to the real world?", 0.35, "theme_interpretation"),
    ("Why is this issue relevant today?", 0.25, "theme_interpretation"),
    ("What social or global issues appear in this text?", 0.30, "theme_interpretation"),
    ("Is there injustice or inequality presented in the text?", 0.35, "theme_interpretation"),
    ("What cultural assumptions are present?", 0.35, "theme_interpretation"),
    ("How does the text construct identity or represent culture?", 0.40, "theme_interpretation"),
    ("How does language reflect social or cultural power in the text?", 0.40, "theme_interpretation"),
    ("How does the author use language to show class, gender, power, or identity?", 0.45, "theme_interpretation"),
    ("How does the reader's background influence how they understand the text?", 0.20, "theme_interpretation"),
    ("What modern perspectives change the way we read this work today?", 0.25, "theme_interpretation"),
    ("Why might this text remain relevant?", 0.25, "theme_interpretation"),
    ("What themes might become more important today than at the time of publication?", 0.25, "theme_interpretation"),
    ("How does a text's meaning or importance change as society changes?", 0.20, "theme_interpretation"),
    ("How might readers in the past have understood this text differently from modern readers?", 0.25, "theme_interpretation"),
    ("Which themes or ideas feel more important today, and why?", 0.25, "theme_interpretation"),
    ("How do texts reflect and shape cultural traditions and behavior?", 0.25, "theme_interpretation"),
    ("What cultural practices or social norms are shown in this text?", 0.35, "theme_interpretation"),
    ("How might this text influence the way people think about these practices?", 0.30, "theme_interpretation"),
    ("What does this text help you understand about the world or about yourself?", 0.20, "theme_interpretation"),
    ("What kinds of things can literature teach us about people, society, or the world?", 0.10, "theme_interpretation"),
    ("How does the author use perspective to influence the reader?", 0.45, "theme_interpretation"),
    ("What does this text reveal about the values, traditions, or social issues of its culture?", 0.35, "theme_interpretation"),

    # ── character_analysis ─────────────────────────────────────────────────
    ("Which are the main, secondary and episodic characters of this book?", 0.25, "character_analysis"),
    ("Which characters represent some aspect of the author's identity?", 0.35, "character_analysis"),
    ("Which characters do you find similar to your personality?", 0.20, "character_analysis"),
    ("Which characters do you identify with?", 0.20, "character_analysis"),
    ("Which character from this book do you really admire?", 0.20, "character_analysis"),
    ("How recognizable are the characters and their attitudes?", 0.30, "character_analysis"),
    ("How much are the characters and their attitudes similar to real people?", 0.25, "character_analysis"),
    ("To what extent have you identified with or felt challenged by the perspectives offered in the book?", 0.25, "character_analysis"),
    ("How does the content and structure of the work make this character stand out among the others in the book?", 0.55, "character_analysis"),
    ("How does the narrator's voice or point of view influence your understanding of the story?", 0.50, "character_analysis"),
    ("How do differences in age, gender, background, or identity shape the viewpoints shown?", 0.40, "character_analysis"),
    ("How far do you think it was the intention of the work to elicit this response in you?", 0.35, "character_analysis"),
    ("Which perspectives are given more importance or more space in the text? Why?", 0.55, "character_analysis"),
    ("What perspectives are missing or underrepresented in the text?", 0.50, "character_analysis"),
    ("Can opposing perspectives in the same text both be meaningful or valid? Why or why not?", 0.30, "character_analysis"),
    ("How does including multiple viewpoints deepen your understanding of the issue?", 0.35, "character_analysis"),
    ("How does this text present different viewpoints on the same topic or conflict?", 0.50, "character_analysis"),

    # ── literary_technique ─────────────────────────────────────────────────
    ("Which literary devices are most important in this extract (e.g., symbolism, irony, narrative voice)?", 0.80, "literary_technique"),
    ("How do these techniques contribute to meaning?", 0.55, "literary_technique"),
    ("What techniques does the author use to create meaning (language, imagery, symbolism, narration)?", 0.50, "literary_technique"),
    ("How does the author's stylistic voice (tone, register, sentence structure) influence interpretation?", 0.55, "literary_technique"),
    ("How does the author use language to shape meaning and tone?", 0.55, "literary_technique"),
    ("In what ways does the use of language in the works you have read represent in itself a view of the world?", 0.50, "literary_technique"),
    ("How do these language choices shape the reader's experience?", 0.50, "literary_technique"),
    ("How does structure, language, and style support this argument?", 0.60, "literary_technique"),
    ("How does the organization of the text (chapters, scenes, chronology) guide understanding?", 0.55, "literary_technique"),
    ("How is the text organized (chapters, scenes, timeline)?", 0.55, "literary_technique"),
    ("How does this structure help develop ideas, characters, or tension?", 0.60, "literary_technique"),
    ("What language choices (tone, imagery, description) shape how you imagine the setting or characters?", 0.60, "literary_technique"),
    ("How does the author use or adapt these conventions?", 0.50, "literary_technique"),
    ("What is the effect of using an unreliable narrator on the reader's trust and interpretation?", 0.55, "literary_technique"),
    ("How does delayed revelation of information shape suspense or reader engagement?", 0.60, "literary_technique"),
    ("What effect does starting a story in the middle or end of a character's life have on the reader's understanding?", 0.60, "literary_technique"),
    ("Why would an author intentionally create uncertainty for the reader?", 0.40, "literary_technique"),
    ("How should readers deal with ambiguity or incomplete information in a text?", 0.35, "literary_technique"),
    ("How does the chosen literary form help show character development or personal growth?", 0.55, "literary_technique"),
    ("Which stylistic or structural elements make this text clearly belong to this form?", 0.50, "literary_technique"),
    ("What differences do you notice when you compare this form to another literary form?", 0.15, "literary_technique"),
    ("Has this type of text changed over time? If yes, how?", 0.10, "literary_technique"),
    ("Do you think this form still follows traditional rules, or does it challenge them? Explain.", 0.35, "literary_technique"),
    ("How does the way a text is built and written influence its message?", 0.40, "literary_technique"),
    ("How do texts help us understand the world while also questioning our beliefs?", 0.20, "literary_technique"),
    ("How does language show social groups and identities?", 0.30, "literary_technique"),
    ("How do these language choices affect the reader's understanding of characters or society?", 0.45, "literary_technique"),
    ("How does the author's language choices (imagery, word choice, symbols) shape what the text communicates?", 0.55, "literary_technique"),
    ("How do the form and structure of the text (for example layout, chapters, scenes, or patterns) help create meaning?", 0.55, "literary_technique"),
    ("Why do you think the author chose this structure instead of another one?", 0.55, "literary_technique"),
    ("How would the meaning change if the structure or style were different?", 0.60, "literary_technique"),
    ("How can different literary techniques (imagery, dialogue, symbolism) lead to similar emotional or ideological effects?", 0.45, "literary_technique"),
    ("Why might an author choose one literary form instead of another to communicate a specific message?", 0.40, "literary_technique"),
    ("What can you learn by comparing different translations of the same text?", 0.30, "literary_technique"),
    ("How can adaptations (films, stage versions, rewrites) reveal new meanings in the original text?", 0.35, "literary_technique"),
    ("How does the format change your understanding or emotional response?", 0.35, "literary_technique"),

    # ── specific_text_analysis ─────────────────────────────────────────────
    ("Which moments or passages affected you most, and why?", 0.65, "specific_text_analysis"),
    ("Which quotations best support your interpretation?", 0.75, "specific_text_analysis"),
    ("How does this quotation connect to a theme, character, or stylistic feature?", 0.80, "specific_text_analysis"),
    ("What is your main argument (thesis) about the text?", 0.65, "specific_text_analysis"),
    ("What evidence supports your analysis or evaluation?", 0.70, "specific_text_analysis"),
    ("How many possible interpretations of the work are you reading or which of its elements can you find? Give me at least 2 examples of such interpretations.", 0.65, "specific_text_analysis"),
    ("What possible interpretations can you already identify?", 0.55, "specific_text_analysis"),
    ("How is this issue presented through characters or events?", 0.65, "specific_text_analysis"),
    ("How does the author guide the reader's understanding through language and structure?", 0.60, "specific_text_analysis"),
    ("What aspects of the text challenge your assumptions, values, or comfort zone?", 0.55, "specific_text_analysis"),
    ("How does the cultural context of the work you are studying at the moment revealed?", 0.55, "specific_text_analysis"),
    ("What is your own interpretation of this text? What evidence supports it?", 0.70, "specific_text_analysis"),
    ("How might critics or readers from the past or present interpret this text differently?", 0.45, "specific_text_analysis"),
    ("What new perspective does your response offer?", 0.50, "specific_text_analysis"),
    ("Do you consider the work you are analysing now as effective in creating a new world in your mind? Why? What contributes to the creation of that world?", 0.40, "specific_text_analysis"),
    ("How does a work make its reader creative when it comes to exploring the possible different meanings of that work?", 0.40, "specific_text_analysis"),
    ("What is the main topic of this book?", 0.25, "specific_text_analysis"),
    ("How accessible is this work to you as a reader?", 0.15, "specific_text_analysis"),
    ("What might prevent a reader understanding this work?", 0.20, "specific_text_analysis"),
    ("What types of evidence should you use to support your ideas (quotes, techniques, context)?", 0.10, "specific_text_analysis"),
    ("Why is explanation more important than just quoting?", 0.05, "specific_text_analysis"),
    ("How will you structure your response to meet the command term?", 0.05, "specific_text_analysis"),
    ("What exactly is the question asking you to do?", 0.05, "specific_text_analysis"),
    ("Can you explain this term clearly in your own words?", 0.05, "specific_text_analysis"),
    ("Are there alternative interpretations you should address?", 0.45, "specific_text_analysis"),
    ("What work from the ones you read till now has changed your thinking? What is being transformed: your views on reading, on writing or on an issue?", 0.15, "specific_text_analysis"),
    ("Which ideas, themes, or messages from these works stayed with you most?", 0.30, "specific_text_analysis"),
    ("What is the central idea or message of this work?", 0.30, "specific_text_analysis"),
    ("How does this text follow the usual rules of its literary form, and how does it break or change them?", 0.55, "specific_text_analysis"),
    ("What new ideas, perspectives, or social issues does the text help you understand?", 0.30, "specific_text_analysis"),
    ("How does the narrator's voice or point of view influence your understanding of the story?", 0.50, "specific_text_analysis"),

    # ── comparative_cross_text ─────────────────────────────────────────────
    ("Compare two works that you have read in the course. How does comparing them change how you understand each work? How do the works seem different after this comparison?", 0.40, "comparative_cross_text"),
    ("What themes are shared between the two works? How are they treated differently?", 0.45, "comparative_cross_text"),
    ("How do the authors' stylistic choices shape meaning in each text?", 0.55, "comparative_cross_text"),
    ("What similarities or differences exist in narrative voice or perspective?", 0.55, "comparative_cross_text"),
    ("How does context influence the messages of each work?", 0.50, "comparative_cross_text"),
    ("What shared human experiences (for example love, loss, migration, identity) connect the texts you are studying?", 0.40, "comparative_cross_text"),
    ("What patterns of connection can you identify across your selected works?", 0.50, "comparative_cross_text"),
    ("How has comparing this text with another work changed your understanding of both texts?", 0.50, "comparative_cross_text"),
    ("How can very different texts still share similar ideas, themes, or techniques?", 0.35, "comparative_cross_text"),
    ("How can different artistic methods produce similar reader responses?", 0.30, "comparative_cross_text"),
    ("What patterns or ideas become clearer when you read multiple works by the same author?", 0.40, "comparative_cross_text"),
    ("How can reading several texts by one writer deepen your understanding of their themes or style?", 0.35, "comparative_cross_text"),
    ("How does recognizing references to other texts change your understanding of a story?", 0.45, "comparative_cross_text"),
    ("What new insights can you gain by reading two texts that explore the same theme in different ways?", 0.45, "comparative_cross_text"),
    ("How can texts from very different cultures or time periods achieve the same overall purpose or message?", 0.30, "comparative_cross_text"),
    ("How can studying older and newer versions of the same genre help you understand literary evolution?", 0.20, "comparative_cross_text"),
    ("How do texts from the same literary form show gradual change across generations?", 0.20, "comparative_cross_text"),
    ("How do changing social values influence the way literary forms are adapted over time?", 0.20, "comparative_cross_text"),
    ("What similarities can you find between changes in literature and changes in other cultural forms (fashion, music, art)?", 0.20, "comparative_cross_text"),
    ("How does comparing texts and interpreting them change the way you understand literature or the world?", 0.30, "comparative_cross_text"),
    ("In which ways the global issue of your choice is presented through the content and form of two of the works that you have studied?", 0.50, "comparative_cross_text"),
    ("How can one text present different points of view about the same topic or theme?", 0.45, "comparative_cross_text"),
    ("How can comparing texts and interpreting them change the way you understand literature or the world?", 0.30, "comparative_cross_text"),

    # ── transformation_creative ────────────────────────────────────────────
    ("Write an alternative ending or part of the book you are reading that changes its interpretation, but that tries to replicate the author's style.", 0.75, "transformation_creative"),
    ("How can you reinterpret the text creatively (monologue, diary entry, alternative ending)?", 0.65, "transformation_creative"),
    ("How does your creative response stay faithful to the original text?", 0.65, "transformation_creative"),
    ("What stylistic elements are essential to preserve the message?", 0.65, "transformation_creative"),
    ("What themes or characters will you highlight in your response?", 0.60, "transformation_creative"),
    ("How would meaning shift if the narrator or perspective changed?", 0.60, "transformation_creative"),
    ("What would change if this text were written in another genre or medium?", 0.55, "transformation_creative"),
    ("How would the text change if written in a different time period?", 0.50, "transformation_creative"),
    ("What happens if the setting is modernized or relocated?", 0.60, "transformation_creative"),
    ("Which character, moment, or conflict do you want to explore creatively?", 0.60, "transformation_creative"),
    ("How can you show understanding of the original text through your creative response?", 0.65, "transformation_creative"),
    ("What tone and style will you adopt to match or contrast the author's voice?", 0.60, "transformation_creative"),
    ("How does your creative piece reflect the themes or issues of the original work?", 0.65, "transformation_creative"),
    ("Which elements must remain unchanged to preserve the author's core message?", 0.65, "transformation_creative"),
    ("What transformation would best highlight the central theme?", 0.60, "transformation_creative"),
    ("How would meaning shift if you changed the narrator, tense, or point of view?", 0.60, "transformation_creative"),
    ("What would change if this text were rewritten in another form (play to short story, novel to poem, prose to script)?", 0.55, "transformation_creative"),
    ("How would readers from different generations respond emotionally or ethically to this text?", 0.35, "transformation_creative"),
    ("How would readers from different eras interpret this text differently?", 0.30, "transformation_creative"),
    ("What political or social perspectives could influence modern interpretations?", 0.30, "transformation_creative"),
    ("Which elements might be controversial or misunderstood today?", 0.35, "transformation_creative"),
    ("How would readers from marginalized or dominant groups respond differently?", 0.30, "transformation_creative"),
    ("How might readers from different cultures interpret the characters or values differently?", 0.30, "transformation_creative"),
    ("Can transforming a text help clarify ideas that were unclear before?", 0.35, "transformation_creative"),

    # ── highly_specific ────────────────────────────────────────────────────
    ("Summarize chapter 3 of this book", 0.95, "highly_specific"),
    ("What are the key plot events in this work?", 0.80, "highly_specific"),
    ("What are the Seven Commandments in this book?", 0.90, "highly_specific"),
    ("What specific event happens in the opening scene?", 0.90, "highly_specific"),
    ("Analyze this specific quote from the text", 1.00, "highly_specific"),
    ("What does the character say when they first meet?", 0.95, "highly_specific"),
    ("How is the main conflict first introduced in the text?", 0.85, "highly_specific"),
    ("What happens at the climax of this story?", 0.85, "highly_specific"),
    ("How does the story end?", 0.80, "highly_specific"),
    ("Describe the relationship between two specific characters in the text", 0.85, "highly_specific"),
    ("What is the significance of the title in relation to the text?", 0.70, "highly_specific"),
    ("What are the exact words used to describe the setting?", 1.00, "highly_specific"),
    ("What happens in this passage?", 1.00, "highly_specific"),
    ("What does this specific symbol represent in the text?", 0.80, "highly_specific"),
    ("How is a specific scene structured?", 0.85, "highly_specific"),
    ("What foreshadowing appears in chapter 1?", 0.85, "highly_specific"),
    ("What are the key events in the plot of this work?", 0.80, "highly_specific"),
    ("What is said during the confrontation between the main characters?", 0.95, "highly_specific"),
    ("Which specific passage best illustrates the theme of power?", 0.85, "highly_specific"),
]


def seed_context_scores() -> None:
    """Insert all scored questions into the DB if the table is empty. Safe to call multiple times."""
    with get_connection(get_db_path()) as conn:
        existing = conn.execute("SELECT COUNT(*) FROM query_context_scores").fetchone()[0]
        if existing > 0:
            logger.info("seed_context_scores: table already has %d rows, skipping seed", existing)
            return
        conn.executemany(
            "INSERT OR IGNORE INTO query_context_scores (question, score, category) VALUES (?, ?, ?)",
            _QUESTIONS,
        )
        seeded = conn.execute("SELECT COUNT(*) FROM query_context_scores").fetchone()[0]
        logger.info("seed_context_scores: seeded %d questions", seeded)
